#include "radio_binary_io.h"
#include <cerrno>
#include <unistd.h>
namespace RadioBinaryIO { namespace {
bool Exact(FILE* f,void* p,size_t n){return n==0||fread(p,1,n,f)==n;}
bool Put(FILE* f,const std::string& s){return s.empty()||fwrite(s.data(),1,s.size(),f)==s.size();}
bool Header(FILE*& f,const char* path,bool cat,uint32_t& count){f=fopen(path,"rb"); if(!f)return false; uint8_t h[16]; if(!Exact(f,h,16)||(cat?!RadioBinaryCodec::DecodeCatalogHeader(h,16,count):!RadioBinaryCodec::DecodeFavoritesHeader(h,16,count))){fclose(f);f=nullptr;return false;}return true;}
bool Len(FILE* f,uint32_t& n){uint8_t b[4];if(!Exact(f,b,4))return false;n=uint32_t(b[0])|(uint32_t(b[1])<<8)|(uint32_t(b[2])<<16)|(uint32_t(b[3])<<24);return true;}
bool Rec(FILE* f,std::string& s){uint32_t n;if(!Len(f,n)||n<4||n>RadioBinaryCodec::kMaxRecordLength)return false;s.assign(n,'\0');s[0]=char(n);s[1]=char(n>>8);s[2]=char(n>>16);s[3]=char(n>>24);return Exact(f,s.data()+4,n-4);}
bool Tail(FILE* f){uint8_t b;return fread(&b,1,1,f)==0;}
}
CatalogReader::~CatalogReader(){if(file_)fclose(file_);} bool CatalogReader::Open(uint32_t& n){return !file_&&Header(file_,path_,true,n)&&((remaining_=n),true);} bool CatalogReader::ReadNext(RadioStationInfo& s){std::string r;if(!file_||failed_||!remaining_||!Rec(file_,r)||!RadioBinaryCodec::DecodeCatalogRecord((const uint8_t*)r.data(),r.size(),s)){failed_=true;return false;}--remaining_;return true;} bool CatalogReader::Finish(){if(!file_||failed_||remaining_||!Tail(file_)){if(file_)fclose(file_);file_=nullptr;return false;}bool ok=fclose(file_)==0;file_=nullptr;return ok;}
FavoritesReader::~FavoritesReader(){if(file_)fclose(file_);} bool FavoritesReader::Open(uint32_t& n){return !file_&&Header(file_,path_,false,n)&&((remaining_=n),true);} bool FavoritesReader::ReadNext(std::string& u){uint8_t b[2];if(!file_||failed_||!remaining_||!Exact(file_,b,2)){failed_=true;return false;}uint16_t n=uint16_t(b[0])|(uint16_t(b[1])<<8);std::string r(2+n,'\0');r[0]=char(b[0]);r[1]=char(b[1]);if(!n||n>RadioBinaryCodec::kMaxUuidLength||!Exact(file_,r.data()+2,n)||!RadioBinaryCodec::DecodeFavoriteUuid((const uint8_t*)r.data(),r.size(),u)){failed_=true;return false;}--remaining_;return true;} bool FavoritesReader::Finish(){if(!file_||failed_||remaining_||!Tail(file_)){if(file_)fclose(file_);file_=nullptr;return false;}bool ok=fclose(file_)==0;file_=nullptr;return ok;}
CatalogWriter::~CatalogWriter(){if(file_){fclose(file_);unlink(path_);}} bool CatalogWriter::Begin(){if(count_>RadioBinaryCodec::kMaxRecords)return false;unlink(path_);std::string h;if(!RadioBinaryCodec::EncodeCatalogHeader(count_,h))return false;file_=fopen(path_,"wb");if(!file_||!Put(file_,h)){if(file_)fclose(file_);file_=nullptr;unlink(path_);return false;}return true;} bool CatalogWriter::Write(const RadioStationInfo& s){std::string r;if(!file_||failed_||written_>=count_||!RadioBinaryCodec::EncodeCatalogRecord(s,r)||!Put(file_,r)){failed_=true;return false;}++written_;return true;} bool CatalogWriter::Finish(){if(!file_||failed_||written_!=count_||fflush(file_)!=0){if(file_)fclose(file_);file_=nullptr;unlink(path_);return false;}bool ok=fclose(file_)==0;file_=nullptr;if(!ok)unlink(path_);return ok;}
FavoritesWriter::~FavoritesWriter(){if(file_){fclose(file_);unlink(path_);}} bool FavoritesWriter::Begin(){if(count_>RadioBinaryCodec::kMaxRecords)return false;unlink(path_);std::string h;if(!RadioBinaryCodec::EncodeFavoritesHeader(count_,h))return false;file_=fopen(path_,"wb");if(!file_||!Put(file_,h)){if(file_)fclose(file_);file_=nullptr;unlink(path_);return false;}return true;} bool FavoritesWriter::Write(const std::string& u){std::string r;if(!file_||failed_||written_>=count_||!RadioBinaryCodec::EncodeFavoriteUuid(u,r)||!Put(file_,r)){failed_=true;return false;}++written_;return true;} bool FavoritesWriter::Finish(){if(!file_||failed_||written_!=count_||fflush(file_)!=0){if(file_)fclose(file_);file_=nullptr;unlink(path_);return false;}bool ok=fclose(file_)==0;file_=nullptr;if(!ok)unlink(path_);return ok;}
bool ReplaceTarget(const char* tmp,const char* target){if(!tmp||!target)return false;if(unlink(target)!=0&&errno!=ENOENT)return false;if(rename(tmp,target)!=0){unlink(tmp);return false;}return true;}
}
